sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy:
  - docker login -u "amatya12" -p "9813445566!"

deploy:
  provider: script
  script: docker push mannydesigns/node
  on:
    branch: master