sudo: required
services:
  - docker

script:
  - docker build -t amatya12/node .
  - docker images amatya12/node

before_deploy:
  - docker login -u "amatya12" -p "9813445566!"

deploy:
  provider: script
  script: docker push amatya12/node
  on:
    branch: master